[2025-03-31T14:06:26.299-0500] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-31T14:06:26.303-0500] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: exec_py.taskA_hw_py manual__2025-03-31T19:06:23.930638+00:00 [queued]>
[2025-03-31T14:06:26.306-0500] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: exec_py.taskA_hw_py manual__2025-03-31T19:06:23.930638+00:00 [queued]>
[2025-03-31T14:06:26.306-0500] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-03-31T14:06:27.544-0500] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): taskA_hw_py> on 2025-03-31 19:06:23.930638+00:00
[2025-03-31T14:06:27.545-0500] {standard_task_runner.py:72} INFO - Started process 461319 to run task
[2025-03-31T14:06:27.547-0500] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'exec_py', 'taskA_hw_py', 'manual__2025-03-31T19:06:23.930638+00:00', '--job-id', '48', '--raw', '--subdir', 'DAGS_FOLDER/exec_py.py', '--cfg-path', '/tmp/tmphrjp2t_2']
[2025-03-31T14:06:27.548-0500] {standard_task_runner.py:105} INFO - Job 48: Subtask taskA_hw_py
[2025-03-31T14:06:27.689-0500] {task_command.py:467} INFO - Running <TaskInstance: exec_py.taskA_hw_py manual__2025-03-31T19:06:23.930638+00:00 [running]> on host royal-07.cs.wisc.edu
[2025-03-31T14:06:28.102-0500] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='cloud.user' AIRFLOW_CTX_DAG_ID='exec_py' AIRFLOW_CTX_TASK_ID='taskA_hw_py' AIRFLOW_CTX_EXECUTION_DATE='2025-03-31T19:06:23.930638+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-31T19:06:23.930638+00:00'
[2025-03-31T14:06:28.103-0500] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-31T14:06:28.109-0500] {logging_mixin.py:190} INFO - hello A
[2025-03-31T14:06:28.109-0500] {python.py:240} INFO - Done. Returned value was: None
[2025-03-31T14:06:28.112-0500] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-31T14:06:28.112-0500] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=exec_py, task_id=taskA_hw_py, run_id=manual__2025-03-31T19:06:23.930638+00:00, execution_date=20250331T190623, start_date=20250331T190626, end_date=20250331T190628
[2025-03-31T14:06:28.482-0500] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-31T14:06:28.495-0500] {taskinstance.py:3901} INFO - 2 downstream tasks scheduled from follow-on schedule check
[2025-03-31T14:06:28.670-0500] {local_task_job_runner.py:245} INFO - ::endgroup::
