[2025-03-31T12:40:16.935-0500] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-31T12:40:16.939-0500] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: hw.task_hw_with scheduled__2025-03-30T00:00:00+00:00 [queued]>
[2025-03-31T12:40:16.942-0500] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: hw.task_hw_with scheduled__2025-03-30T00:00:00+00:00 [queued]>
[2025-03-31T12:40:16.942-0500] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-03-31T12:40:17.061-0500] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): task_hw_with> on 2025-03-30 00:00:00+00:00
[2025-03-31T12:40:17.063-0500] {standard_task_runner.py:72} INFO - Started process 398421 to run task
[2025-03-31T12:40:17.064-0500] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'hw', 'task_hw_with', 'scheduled__2025-03-30T00:00:00+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/hello_world.py', '--cfg-path', '/tmp/tmp6u4bq0d2']
[2025-03-31T12:40:17.065-0500] {standard_task_runner.py:105} INFO - Job 24: Subtask task_hw_with
[2025-03-31T12:40:17.192-0500] {task_command.py:467} INFO - Running <TaskInstance: hw.task_hw_with scheduled__2025-03-30T00:00:00+00:00 [running]> on host royal-07.cs.wisc.edu
[2025-03-31T12:40:17.783-0500] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='cloud.user' AIRFLOW_CTX_DAG_ID='hw' AIRFLOW_CTX_TASK_ID='task_hw_with' AIRFLOW_CTX_EXECUTION_DATE='2025-03-30T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-30T00:00:00+00:00'
[2025-03-31T12:40:17.783-0500] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-31T12:40:17.810-0500] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-03-31T12:40:17.810-0500] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo "Hello World Again 2"']
[2025-03-31T12:40:17.813-0500] {subprocess.py:99} INFO - Output:
[2025-03-31T12:40:17.814-0500] {subprocess.py:106} INFO - Hello World Again 2
[2025-03-31T12:40:17.814-0500] {subprocess.py:110} INFO - Command exited with return code 0
[2025-03-31T12:40:17.909-0500] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-31T12:40:17.909-0500] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=hw, task_id=task_hw_with, run_id=scheduled__2025-03-30T00:00:00+00:00, execution_date=20250330T000000, start_date=20250331T174016, end_date=20250331T174017
[2025-03-31T12:40:18.160-0500] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-31T12:40:18.166-0500] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-31T12:40:18.167-0500] {local_task_job_runner.py:245} INFO - ::endgroup::
