[2025-03-31T12:50:34.446-0500] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-31T12:50:34.451-0500] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: exec_mult_tasks.1 scheduled__2025-03-30T00:00:00+00:00 [queued]>
[2025-03-31T12:50:34.454-0500] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: exec_mult_tasks.1 scheduled__2025-03-30T00:00:00+00:00 [queued]>
[2025-03-31T12:50:34.454-0500] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-03-31T12:50:34.593-0500] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): 1> on 2025-03-30 00:00:00+00:00
[2025-03-31T12:50:34.594-0500] {standard_task_runner.py:72} INFO - Started process 403779 to run task
[2025-03-31T12:50:34.596-0500] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'exec_mult_tasks', '1', 'scheduled__2025-03-30T00:00:00+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/exec_multiple_tasks.py', '--cfg-path', '/tmp/tmpgyuxsn7r']
[2025-03-31T12:50:34.597-0500] {standard_task_runner.py:105} INFO - Job 25: Subtask 1
[2025-03-31T12:50:34.847-0500] {task_command.py:467} INFO - Running <TaskInstance: exec_mult_tasks.1 scheduled__2025-03-30T00:00:00+00:00 [running]> on host royal-07.cs.wisc.edu
[2025-03-31T12:50:35.097-0500] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='cloud.user' AIRFLOW_CTX_DAG_ID='exec_mult_tasks' AIRFLOW_CTX_TASK_ID='1' AIRFLOW_CTX_EXECUTION_DATE='2025-03-30T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-30T00:00:00+00:00'
[2025-03-31T12:50:35.097-0500] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-31T12:50:35.120-0500] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-03-31T12:50:35.120-0500] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo "Task 1 executed"']
[2025-03-31T12:50:35.123-0500] {subprocess.py:99} INFO - Output:
[2025-03-31T12:50:35.124-0500] {subprocess.py:106} INFO - Task 1 executed
[2025-03-31T12:50:35.124-0500] {subprocess.py:110} INFO - Command exited with return code 0
[2025-03-31T12:50:35.233-0500] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-31T12:50:35.233-0500] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=exec_mult_tasks, task_id=1, run_id=scheduled__2025-03-30T00:00:00+00:00, execution_date=20250330T000000, start_date=20250331T175034, end_date=20250331T175035
[2025-03-31T12:50:35.530-0500] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-31T12:50:35.645-0500] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-31T12:50:35.770-0500] {local_task_job_runner.py:245} INFO - ::endgroup::
