[2025-03-31T13:13:44.739-0500] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-31T13:13:44.743-0500] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: exec_mult_tasks.taskA manual__2025-03-31T18:13:41.058846+00:00 [queued]>
[2025-03-31T13:13:44.745-0500] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: exec_mult_tasks.taskA manual__2025-03-31T18:13:41.058846+00:00 [queued]>
[2025-03-31T13:13:44.746-0500] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-03-31T13:13:44.882-0500] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): taskA> on 2025-03-31 18:13:41.058846+00:00
[2025-03-31T13:13:44.884-0500] {standard_task_runner.py:72} INFO - Started process 421660 to run task
[2025-03-31T13:13:44.886-0500] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'exec_mult_tasks', 'taskA', 'manual__2025-03-31T18:13:41.058846+00:00', '--job-id', '37', '--raw', '--subdir', 'DAGS_FOLDER/exec_multiple_tasks.py', '--cfg-path', '/tmp/tmpcg6lniyh']
[2025-03-31T13:13:44.886-0500] {standard_task_runner.py:105} INFO - Job 37: Subtask taskA
[2025-03-31T13:13:45.028-0500] {task_command.py:467} INFO - Running <TaskInstance: exec_mult_tasks.taskA manual__2025-03-31T18:13:41.058846+00:00 [running]> on host royal-07.cs.wisc.edu
[2025-03-31T13:13:45.168-0500] {abstractoperator.py:783} ERROR - Exception rendering Jinja template for task 'taskA', field 'bash_command'. Template: 'taskA.sh'
Traceback (most recent call last):
  File "/home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/models/abstractoperator.py", line 775, in _do_render_template_fields
    rendered_content = self.render_template(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/template/templater.py", line 168, in render_template
    template = jinja_env.get_template(value)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/udhbhav/miniconda3/lib/python3.11/site-packages/jinja2/environment.py", line 1016, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/udhbhav/miniconda3/lib/python3.11/site-packages/jinja2/environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/udhbhav/miniconda3/lib/python3.11/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/udhbhav/miniconda3/lib/python3.11/site-packages/jinja2/loaders.py", line 209, in get_source
    raise TemplateNotFound(
jinja2.exceptions.TemplateNotFound: 'taskA.sh' not found in search paths: '/home/udhbhav/airflow/dags', './bash_scripts'
[2025-03-31T13:13:45.230-0500] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3117, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context, jinja_env=jinja_env)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3540, in render_templates
    original_task.render_template_fields(context, jinja_env)
  File "/home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 1442, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/models/abstractoperator.py", line 775, in _do_render_template_fields
    rendered_content = self.render_template(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/template/templater.py", line 168, in render_template
    template = jinja_env.get_template(value)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/udhbhav/miniconda3/lib/python3.11/site-packages/jinja2/environment.py", line 1016, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/udhbhav/miniconda3/lib/python3.11/site-packages/jinja2/environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/udhbhav/miniconda3/lib/python3.11/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/udhbhav/miniconda3/lib/python3.11/site-packages/jinja2/loaders.py", line 209, in get_source
    raise TemplateNotFound(
jinja2.exceptions.TemplateNotFound: 'taskA.sh' not found in search paths: '/home/udhbhav/airflow/dags', './bash_scripts'
[2025-03-31T13:13:45.232-0500] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=exec_mult_tasks, task_id=taskA, run_id=manual__2025-03-31T18:13:41.058846+00:00, execution_date=20250331T181341, start_date=20250331T181344, end_date=20250331T181345
[2025-03-31T13:13:45.642-0500] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-31T13:13:45.642-0500] {standard_task_runner.py:124} ERROR - Failed to execute job 37 for task taskA ('taskA.sh' not found in search paths: '/home/udhbhav/airflow/dags', './bash_scripts'; 421660)
Traceback (most recent call last):
  File "/home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3117, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context, jinja_env=jinja_env)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3540, in render_templates
    original_task.render_template_fields(context, jinja_env)
  File "/home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 1442, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/models/abstractoperator.py", line 775, in _do_render_template_fields
    rendered_content = self.render_template(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/template/templater.py", line 168, in render_template
    template = jinja_env.get_template(value)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/udhbhav/miniconda3/lib/python3.11/site-packages/jinja2/environment.py", line 1016, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/udhbhav/miniconda3/lib/python3.11/site-packages/jinja2/environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/udhbhav/miniconda3/lib/python3.11/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/udhbhav/miniconda3/lib/python3.11/site-packages/jinja2/loaders.py", line 209, in get_source
    raise TemplateNotFound(
jinja2.exceptions.TemplateNotFound: 'taskA.sh' not found in search paths: '/home/udhbhav/airflow/dags', './bash_scripts'
[2025-03-31T13:13:45.660-0500] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-31T13:13:46.603-0500] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-31T13:13:46.841-0500] {local_task_job_runner.py:245} INFO - ::endgroup::
